[2024-06-05T22:37:53.013+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T22:37:53.033+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_top_games.fetch_top_games manual__2024-06-05T20:37:34.054783+00:00 [queued]>
[2024-06-05T22:37:53.039+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_top_games.fetch_top_games manual__2024-06-05T20:37:34.054783+00:00 [queued]>
[2024-06-05T22:37:53.039+0200] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-06-05T22:37:53.071+0200] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): fetch_top_games> on 2024-06-05 20:37:34.054783+00:00
[2024-06-05T22:37:53.075+0200] {standard_task_runner.py:63} INFO - Started process 53875 to run task
[2024-06-05T22:37:53.083+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_top_games', 'fetch_top_games', 'manual__2024-06-05T20:37:34.054783+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpw6o6lbc8']
[2024-06-05T22:37:53.086+0200] {standard_task_runner.py:91} INFO - Job 19: Subtask fetch_top_games
[2024-06-05T22:37:53.153+0200] {task_command.py:426} INFO - Running <TaskInstance: fetch_top_games.fetch_top_games manual__2024-06-05T20:37:34.054783+00:00 [running]> on host LAPTOP-R4RVPDJS.
[2024-06-05T22:37:53.393+0200] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fetch_top_games' AIRFLOW_CTX_TASK_ID='fetch_top_games' AIRFLOW_CTX_EXECUTION_DATE='2024-06-05T20:37:34.054783+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-05T20:37:34.054783+00:00'
[2024-06-05T22:37:53.394+0200] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T22:37:53.826+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T22:37:53.827+0200] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/louis/GamingDataPipeline/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/louis/GamingDataPipeline/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/louis/GamingDataPipeline/airflow_venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/louis/GamingDataPipeline/airflow_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/louis/GamingDataPipeline/airflow_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/louis/GamingDataPipeline/scripts/pipeline_etl.py", line 91, in fetch_and_store_top_games
    cur.execute(upsert_query,(
psycopg2.errors.UndefinedColumn: column excluded.note_plus_rescente does not exist
LINE 9:             note_plus_rescente = EXCLUDED.note_plus_rescente...
                                         ^
HINT:  Perhaps you meant to reference the column "excluded.note_plus_recente".

[2024-06-05T22:37:53.830+0200] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_top_games, task_id=fetch_top_games, execution_date=20240605T203734, start_date=20240605T203753, end_date=20240605T203753
[2024-06-05T22:37:53.870+0200] {standard_task_runner.py:110} ERROR - Failed to execute job 19 for task fetch_top_games (column excluded.note_plus_rescente does not exist
LINE 9:             note_plus_rescente = EXCLUDED.note_plus_rescente...
                                         ^
HINT:  Perhaps you meant to reference the column "excluded.note_plus_recente".
; 53875)
[2024-06-05T22:37:53.901+0200] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-05T22:37:53.927+0200] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-05T22:37:53.928+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
